import daisyui from "daisyui";
/** @type {import('tailwindcss').Config} */

export default {
  plugins: [daisyui],
  daisyui: { themes: [], logs: false },
  content: ["./**/*.tsx"],
  theme: {
    container: { center: true },
    extend: {
      fontFamily: {
        afacad: "Afacad, sans-serif",
        josefin: "Josefin Sans, sans-serif",
      },
      colors: {
        "primary": "#98B020",
        "blue-1": "#006EFF",
        "blue-2": "#00B4FF",
        "green-1": "#45D268",
        "orange-1": "#FF8C00",
        "black-1": "#191C1F",
        "black-2": "#1A1A1A",
        "gray-1": "#4A4845",
        "gray-2": "#8E8E93",
        "gray-3": "#ACACAC",
        "gray-4": "#E4F0FF",
        "gray-5": "#5E5E5E",
        "gray-6": "#f1f1f1",
        "gray-7": "#707070",
        "gray-8": "#E5E5EA",
        "gray-9": "#F4F4F4",
        "gray-10": "#EFEFF4",
        "gray-11": "#344054",
        "gray-12": "#F3F3F3",
        "gray-13": "#979797",
        "gray-14": "#DADADA",
        "gray-15": "#EFEFEF",
        "gray-16": "#E9ECEF",
        "gray-17": "#F8F8F8",
        "gray-18": "#F5F5F5",
        "white-1": "#F6F6F6",
      },
      boxShadow: {
        "simpleBanner": "0px 4px 20px 0px #0000004D",
      },
      fontSize: {
        tiny: "10px",
        small: "12px",
        base: "14px",
        big: "16px",
        bigger: "18px",
        large: "20px",
        larger: "22px",
        xlarge: "24px",
      },
      screens: {
        // Intervals
        "dv-full-desktop": { "max": "1920px", "min": "1600px" },
        "dv-lg-desktop": { "max": "1599px", "min": "1441px" },
        "dv-sm-desktop": { "max": "1440px", "min": "1367px" },
        "dv-lg-laptop": { "max": "1366px", "min": "1281px" },
        "dv-sm-laptop": { "max": "1280px", "min": "1200px" },
        "dv-all-tablet": { "max":"1024px", "min":"639px" },
        "dv-full-tablet": { "max": "1199px", "min": "1078px" },
        "dv-lg-tablet": { "max": "1077px", "min": "1025px" },
        "dv-md-tablet": { "max": "1024px", "min": "821px" },
        "dv-sm-tablet": { "max": "820px", "min": "769px" },
        "dv-xsm-tablet": { "max": "768px", "min": "639px" },
        "dv-full-phone": { "max": "638px", "min": "431px" },
        "dv-lg-phone": { "max": "430px", "min": "391px" },
        "dv-md-phone": { "max": "390px", "min": "376px" },
        "dv-sm-phone": { "max": "375px", "min": "361px" },
        "dv-xsm-phone": { "max": "360px", "min": "321px" },

        // Custom
        "cs-min-full-phone": { "min": "639px" },
        "cs-min-full-desktop": { "min": "1025px" },
        "cs-all-sm-tablet": {"min": "1025px", "max": "1199px"},
        "cs-all-tablet": { "min": "639px", "max": "1024px" },

        // Max widths
        "full-desktop": { "max": "1920px" },
        "lg-desktop": { "max": "1599px" },
        "sm-desktop": { "max": "1440px" },
        "lg-laptop": { "max": "1366px" },
        "sm-laptop": { "max": "1280px" },
        "full-tablet": {"max": "1199px" },
        "lg-tablet": { "max": "1077px" },
        "md-tablet": { "max": "1024px" },
        "sm-tablet": { "max": "820px" },
        "xsm-tablet": { "max": "768px" },
        "full-phone": { "max": "638px" },
        "lg-phone": { "max": "430px" },
        "md-phone": { "max": "390px" },
        "sm-phone": { "max": "375px" },
        "xsm-phone": { "max": "360px" },
        "xxsm-phone": { "max": "320px" },
      },
      animation: {
        sliding: "sliding 30s linear infinite",
      },
      keyframes: {
        sliding: {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
      },
    },
  },
};
